### ISSUE TITLE
use with keyword for file objects

### ISSUE THREAD

**Issue by sanyer** [Spazzy757/plagirism-checker#1]
It is good practice to use the with keyword when dealing with file objects.

**Comment by Spazzy757** [comment]
I don't think its specifically "best practice", the use of `with` just handles the closing of the file after the operations for me the feeling is that this is implicit, vs the explicit actions of closing the file (`file.close()`). 

The Zen of Python, by Tim Peters
```
Explicit is better than implicit.
```

True `with` will close the file if exceptions happen but you should also be handling exceptions. I specifically develop python with a very opinionated view :)

```
“The with statement simplifies exception handling by encapsulating common preparation and cleanup tasks.”
```

Simplifying codes sometimes you lose the ideologies behind it


I would not specifically see this as an issue until usage resulted in corrupted files (which it hasn't as of yet) so I will close this

**Comment by sanyer** [comment]
It is recognized as good practice by Python developers: [7.2. Reading and Writing Files](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files):
```
It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point. Using with is also much shorter than writing equivalent try-finally blocks
```

`Explicit is better than implicit` is a rule for your own code and not the language syntax.
And even then context manager is not just some regular syntactic sugar or code simplification, no. It defines the runtime context for the code block, thus making it also easier to read. And specifically `with` keyword have had severals years worth of discussion and was accepted 15 years ago as [PEP 343](https://www.python.org/dev/peps/pep-0343/).

All in all, you can of course develop as opinionated as you want. I just don't agree with the approach of ignoring well-tested and widely accepted constructions (which are not even new anymore). It reminds me of luddite movement.
Just shared my opinion, I guess there is no need to find out who is right and who is not, we both may be.

Oh, I also created this issue just to do a basic pull request, so I can start helping :-)
